[package]
name = "email_registry"
type = "contract"
authors = ["Cheetah0x"]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "aztec-packages-v0.76.1", directory = "noir-projects/aztec-nr/aztec" }
rsa = { tag = "v0.5.1", git = "https://github.com/noir-lang/noir_rsa/", directory = "lib" }
bignum = { tag = "v0.5.2", git = "https://github.com/noir-lang/noir-bignum" }
string_search = { tag = "v0.3.0", git = "https://github.com/noir-lang/noir_string_search/" }
nodash = { git = "https://github.com/olehmisar/nodash/", tag = "v0.39.6" }
