/* Autogenerated file, do not edit! */

/* eslint-disable */
import {
  type AbiType,
  AztecAddress,
  type AztecAddressLike,
  CompleteAddress,
  Contract,
  type ContractArtifact,
  ContractBase,
  ContractFunctionInteraction,
  type ContractInstanceWithAddress,
  type ContractMethod,
  type ContractStorageLayout,
  type ContractNotes,
  decodeFromAbi,
  DeployMethod,
  EthAddress,
  type EthAddressLike,
  EventSelector,
  type FieldLike,
  Fr,
  type FunctionSelectorLike,
  L1EventPayload,
  loadContractArtifact,
  type NoirCompiledContract,
  NoteSelector,
  Point,
  type PublicKey,
  PublicKeys,
  type UnencryptedL2Log,
  type Wallet,
  type U128Like,
  type WrappedFieldLike,
} from "@aztec/aztec.js";
import EmailRegistryContractArtifactJson from "../registry/target/email_registry-EmailRegistry.json" assert { type: "json" };
export const EmailRegistryContractArtifact = loadContractArtifact(
  EmailRegistryContractArtifactJson as NoirCompiledContract
);

/**
/**
 * Type-safe interface for contract EmailRegistry;
 */
export class EmailRegistryContract extends ContractBase {
  private constructor(instance: ContractInstanceWithAddress, wallet: Wallet) {
    super(instance, EmailRegistryContractArtifact, wallet);
  }

  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A promise that resolves to a new Contract instance.
   */
  public static async at(address: AztecAddress, wallet: Wallet) {
    return Contract.at(
      address,
      EmailRegistryContract.artifact,
      wallet
    ) as Promise<EmailRegistryContract>;
  }

  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, admin: AztecAddressLike) {
    return new DeployMethod<EmailRegistryContract>(
      PublicKeys.default(),
      wallet,
      EmailRegistryContractArtifact,
      EmailRegistryContract.at,
      Array.from(arguments).slice(1)
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(
    publicKeys: PublicKeys,
    wallet: Wallet,
    admin: AztecAddressLike
  ) {
    return new DeployMethod<EmailRegistryContract>(
      publicKeys,
      wallet,
      EmailRegistryContractArtifact,
      EmailRegistryContract.at,
      Array.from(arguments).slice(2)
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<
    M extends keyof EmailRegistryContract["methods"]
  >(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<EmailRegistryContract["methods"][M]>
  ) {
    return new DeployMethod<EmailRegistryContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      EmailRegistryContractArtifact,
      EmailRegistryContract.at,
      Array.from(arguments).slice(1),
      opts.method ?? "constructor"
    );
  }

  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return EmailRegistryContractArtifact;
  }

  public static get storage(): ContractStorageLayout<
    "admin" | "emails" | "jwks_allowlist"
  > {
    return {
      admin: {
        slot: new Fr(1n),
      },
      emails: {
        slot: new Fr(2n),
      },
      jwks_allowlist: {
        slot: new Fr(3n),
      },
    } as ContractStorageLayout<"admin" | "emails" | "jwks_allowlist">;
  }

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    /** add_email(jwt: struct) */
    add_email: ((jwt: {
      header_and_payload: {
        storage: (bigint | number)[];
        len: bigint | number;
      };
      payload_json: (bigint | number)[];
      signature_limbs: FieldLike[];
      jwt_iat: bigint | number;
      public_key_e: FieldLike;
      public_key_limbs: FieldLike[];
      public_key_redc_limbs: FieldLike[];
      jwt_id: FieldLike;
      jwt_nonce: (bigint | number)[];
      email_bytes: (bigint | number)[];
    }) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** add_jwk(jwt_id: field) */
    add_jwk: ((jwt_id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** change_email(old_email_hash: field, jwt: struct) */
    change_email: ((
      old_email_hash: FieldLike,
      jwt: {
        header_and_payload: {
          storage: (bigint | number)[];
          len: bigint | number;
        };
        payload_json: (bigint | number)[];
        signature_limbs: FieldLike[];
        jwt_iat: bigint | number;
        public_key_e: FieldLike;
        public_key_limbs: FieldLike[];
        public_key_redc_limbs: FieldLike[];
        jwt_id: FieldLike;
        jwt_nonce: (bigint | number)[];
        email_bytes: (bigint | number)[];
      }
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** compute_note_hash_and_optionally_a_nullifier(contract_address: struct, nonce: field, storage_slot: field, note_type_id: field, compute_nullifier: boolean, packed_note_content: array) */
    compute_note_hash_and_optionally_a_nullifier: ((
      contract_address: AztecAddressLike,
      nonce: FieldLike,
      storage_slot: FieldLike,
      note_type_id: FieldLike,
      compute_nullifier: boolean,
      packed_note_content: FieldLike[]
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** constructor(admin: struct) */
    constructor: ((admin: AztecAddressLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** get_associated_address(email_hash: field) */
    get_associated_address: ((
      email_hash: FieldLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** is_valid_jwk(jwt_id: field) */
    is_valid_jwk: ((jwt_id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** process_log(log_plaintext: struct, tx_hash: field, unique_note_hashes_in_tx: struct, first_nullifier_in_tx: field, recipient: struct) */
    process_log: ((
      log_plaintext: { storage: FieldLike[]; len: bigint | number },
      tx_hash: FieldLike,
      unique_note_hashes_in_tx: { storage: FieldLike[]; len: bigint | number },
      first_nullifier_in_tx: FieldLike,
      recipient: AztecAddressLike
    ) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** remove_email(email_hash: field) */
    remove_email: ((email_hash: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** remove_jwk(jwt_id: field) */
    remove_jwk: ((jwt_id: FieldLike) => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;

    /** sync_notes() */
    sync_notes: (() => ContractFunctionInteraction) &
      Pick<ContractMethod, "selector">;
  };
}
